### ISSUE TITLE
Add customer information to order chat and fix admin view

### ISSUE THREAD

**Issue by Kenny477** [leofuturer/eDrops3#109]
Currently order chat has two problems (one cosmetic, one functionality)
1) Cosmetic problem: chat does not display customer names or identification for the message
2) Functionality: admin viewing customer chat sees messages from both users on the left side
- this needs to be addressed by making it so that for an admin viewing, user and worker messages are separated

**Comment by leofuturer** [comment]
@aditya-am-murthy Will your recent PR #145 fix this issue? If so, please assign this issue to yourself and associate this issue with that PR.
